---
# file: group_vars/all/aws_credentials.yml
#
# Amazon Web Services (AWS) credentials
# http://docs.ansible.com/ansible/guide_aws.html
#
# Make an ansible-vault encrypted copy of this file:
#
# cp aws_credentials.yml aws_credentials.yml.vault
# ansible-vault encrypt aws_credentials.yml.vault
#
# Uncomment and set your credentials in the encrypted file.
#

#
# Your 12-digit account ID may be used to reference
# your account programmatically and in other contexts.
#
#aws_account_id: ""

#
# You use your canonical user ID to configure
# Amazon S3 access control lists (ACLs).
#
#aws_canonical_user_id: ""

#aws_access_key: ""
#aws_secret_key: ""
#ec2_key_pair_name: ""
