# file: group_vars/bastion/packages.yml
---

#
# Packages to install or remove on bastion hosts
#
packages:
#
- name: deltarpm
  state: present
- name: inotify-tools
  state: present
- name: nano
  state: present
- name: screen
  state: present
#
- name: adobe-source-han-sans-tw-fonts
  state: absent
- name: authconfig
  state: absent
- name: cheese
  state: absent
- name: empathy
  state: absent
- name: evolution
  state: absent
- name: firefox
  state: absent
- name: foomatic-db-ppds
  state: absent
- name: ghostscript-core
  state: absent
- name: glib-networking
  state: absent
- name: gnome-backgrounds
  state: absent
- name: gnome-contacts
  state: absent
- name: gnome-font-viewer
  state: absent
- name: gnome-user-docs
  state: absent
- name: gnome-weather
  state: absent
- name: gsettings-desktop-schemas
  state: absent
- name: adobe-source-han-sans-cn-fonts
  state: absent
- name: libreoffice-core
  state: absent
- name: libsoup
  state: absent
- name: microcode_ctl
  state: absent
- name: newt
  state: absent
- name: newt-python
  state: absent
- name: postfix
  state: absent
- name: qt
  state: absent
- name: rhythmbox
  state: absent
- name: shotwell
  state: absent
- name: slang
  state: absent
- name: xfsprogs
  state: absent
